import { chromium } from 'playwright';
const OUT = '/workspace/davidlefkowitz.com/critique/shots-ux';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.goto('http://localhost:8080/fyc/listennow', { waitUntil: 'networkidle' });
await page.waitForTimeout(1200);
await page.screenshot({ path: OUT + '/desktop-fyc-listennow-full.png', fullPage: true });
console.log('fyc/listennow h1/h2:', (await page.locator('h1,h2').allTextContents()).slice(0,4).join(' | '));
await browser.close();
